### ISSUE TITLE
the a.i stopped answering my questions.

### ISSUE THREAD

**Issue by johnshearing** [UmstadAI/zkAppUmstad#37]
I found the a.i to be very helpful but after I asked if it would be possible to spend from an account if there were no archive nodes and if I had lost control of my wallet. I am thinking "no" because active nodes don't know what the balance of my account is, they can only prove a statement about account balance is correct. So I am thinking that even if I have the private key and can set up a new wallet then it would still not be possible to spend from the account with out knowing the balance because only the old wallet or an archive node would be tracking the balance and you need the balance in order to make a proof of the balance which ensures there is enough funds in the account to cover the amount being sent. 

After a while arguing over this point with my intention to understand, the a.i. stopped communicating on any topic.

Later I got an answer to my question on discord: An active node holds a complete ledger of all balances on the Mina blockchain as well as a 22kb proof that the balances are correct. So it seems that as long as active nodes exist and you have your private key, then you will always be able to access your funds.

The a.i. was not able to explain this and finally it stopped responding. In all I found the a.i very helpful in answering all kinds of noob questions before it went offline.

Update:
It's about 6 hours later and I asked if the a.i was online.
The a.i responded that it is and ask how it could help.

I asked the following:
Is it true that all active Mina nodes hold the current balances of all Mina accounts?

At this point my question was deleted and the a.i went silent.

**Comment by berkingurcan** [comment]
Thank you for the report.

I think you have just exceed the daily request limit. After that you should use your own openai api key.
Also, because of context length creating worse results, you should not ask too many questions in the same chat(maybe context was too long for your problem). 

Also, nowadays, OpenAI API is not stable. Always check it from https://status.openai.com/
